### ISSUE TITLE
PHIcalc? example data seems corrupted

### ISSUE THREAD

**Issue by ashtonmj** [leppott/MBSStools#19]
**Describe the bug**
Ran example code from PHIcalc? on 10/18/2018 in R 3.4.0 and see many NA in raw values for PHI data table. Referenced a handful of sites in database and see they should have data. 

**To Reproduce**
1. Go to PHIcalc? http://127.0.0.1:11817/library/MBSStools/html/PHIcalc.html
2. Copy and paste example code into R console and run
3. Visually examine InStrmHab_020 for StationID 1:10 
4. See NA
5. Those sites have Instream Habitat scores

**Expected behavior**
Function ran as expected, but View(PHI) returns table of suspect data

**Screenshots**
![image](https://user-images.githubusercontent.com/39165657/47180602-eae92f00-d2ee-11e8-93e1-453d6b7ce08f.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 Enterprise
 - Browser Chrome
 - Version Unknown

**Comment by leppott** [comment]
The input data (MBSS.PHI) and output from the calculation (PHI) match for the NA values.

![image](https://user-images.githubusercontent.com/24276278/82557055-fb9bff80-9b38-11ea-82f5-4d09516b3094.png)

The input data comes from an Excel file and matches for number of blank cells (20/60 so 40 non-blank).  The Excel file is in the "inst" folder, PHI Worksheet_from MP (Erik20170329).xls and is on the "R_Data" worksheet.

![image](https://user-images.githubusercontent.com/24276278/82557180-3dc54100-9b39-11ea-98c9-fb835707daf7.png)

**Comment by leppott** [comment]
Added "testthat" for PHI calc.

Final result is fine for all 60 example samples.

![image](https://user-images.githubusercontent.com/24276278/82559754-22a90000-9b3e-11ea-8a9a-83aeef1bdc77.png)
