### ISSUE TITLE
Change levels of Exclude for consistency with database export

### ISSUE THREAD

**Issue by ashtonmj** [leppott/MBSStools#25]
**Is your feature request related to a problem? Please describe.**
Benthic macroinvertebrate sample database populates a factor to identify non-unique taxon (EXCLUDE) with levels "TRUE" and "FALSE". MBSStools metric.values.R sets levels of Exclude as "Y" and null. This has created problems reading data in this column when there are long strings of null values and currently requires additional tidying that is not required.

**Describe the solution you'd like**
Change factor for EXCLUDE from "Y" to "TRUE" when the row is a non-unique taxon to establish consistency with level used in the benthic sample database. This change should be applied in the following lines of metric.values.R

212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 226, 245, 246, 247, 255, 256, 257, 258, 259, 277, 278, 279, 280, 281, 289, 290, 291, 295, 296, 297 (twice), 313, and 439

**Describe alternatives you've considered**
We have currently made these changes with additional, personal lines of code or directly in flat files, which is not desired.

**Comment by leppott** [comment]
Update package data for Benthos.  Fish IBI doesn't use "Exclude" field.

- taxa_bugs_family
- taxa_bugs_genus

Update data_raw\ProcessData scripts.

- ProcessData_IBI_taxa_bugs_family.R
- ProcessData_IBI_taxa_bugs_genus.R

Convert field to Logical and TRUE/FALSE rather than Y and "".

devtools::use_data() deprecated.  use usethis::use_data().

**Comment by leppott** [comment]
metric.values.R function

- Help text
- code

EXCLUDE!="Y"
to
EXCLUDE!=FALSE

Use search and replace.

**Comment by leppott** [comment]
Example code for metric.value update myMetrics to use "MetricName.Other" not "Metric".  Otherwise get an error.

Correct in metric.scores examples.
